상단 네비게이션 scroll 이벤트에서 인터섹션옵저버로 성능 최적화
prgrms-web-devcourse/slam-client pull request #182
Opened 2021-12-27 00:24 UTC by manudeli

## 💁 설명 
scroll이벤트에 바인딩된 불필요한 이벤트가 발생되지 않도록 intersectionObserver로 성능 최적화했어요

## 🚨 PR 포인트 
TopnavigationSensor라는 styled컴포넌트를 더 만들어서 이 엘리멘트가 뷰포트와 인터섹션 되었을 때 이벤트가 발생되도록 리팩토링 했어요
혹시 더 좋은 대안이 있다면 알려주시면 감사할게요

## 📸 스크린 샷 
![chrome-capture (8)](https://user-images.githubusercontent.com/61593290/147423454-3f1d3bf6-0922-4b86-9a8e-7140a902ec67.gif)

2021-12-27 00:26 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +`;
Container를 fixed로 만들고 TopNavigationSensor를 통해 인터섹션하는지 검사했습니다.

2022-01-04 14:30 UTC, grighth12 requested changes
pn룰에 따른 첫 리뷰를 남겨 보았습니당
성능 최적화 꼭 하고 싶었는데 신경써서 해주셔서 감사해요~
더 발전할 Navaigation 컴포넌트 와쟈와쟈👏

2022-01-04 14:30 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +  const sensorRef = useRef<HTMLDivElement>(null);
`p2` 저는 보통 감지 대상 ref를 targetRef 라고 이름을 짓는데, 이 부분 sensor 또는 target 으로 맞추면 좋을 것 같아요
전 target을 좀 더 선호합니다~ 마누 의견은 어떠신가요?

2022-01-04 14:30 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +    if (entry) setIsTopTransparent(entry.isIntersecting);
`p1` 한 줄짜리 return 문이더라도 중괄호로 감싸주세요! 이 부분 린트룰에도 추가해야겠네요😅

2022-01-04 14:30 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +                )}
`p3`저는 JSX 구문에 있는 계산식들을 웬만하면 위에서 useMemo를 통해 지역변수화 해서 넣어주는 편이에요 이 경우에도 그래야 할지는 모르겠어서...! 참고만 부탁드립니다 :eyes:

2022-01-04 14:30 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +                userId={userId || 1}
`p1` 아마 userId가 종종 들어오지 않아서 예외처리를 해놓으셨을 거 같아요! 이 예외를 최대한 백엔드와 협의해서 없애고, 이렇게 작성할 코드일 경우에는 주석을 달아주면 좋을 것 같습니다!

ex) // TODO: 발생해서는 안될 예외, 추후 해결 예정

2022-01-04 14:30 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +                  "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png"
`p1`이 부분은 Avatar를 래핑해서 만드셨다면, base/Avatar에 있어야 할 것 같아요!  아니라면 LinkAvatar 컴포넌트 내부에서 조건문을 써서 처리해주는게 좋을 것 같습니다

2022-01-04 14:30 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +              <Link href={`/user/menu`} passHref>
`p3` 요것은 조금 관련 없는 이야기지만 url들도 global constants로 빼줘야 하나 싶은 생각이 슬쩍쿵 드네요

2022-01-04 15:02 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +    if (entry) setIsTopTransparent(entry.isIntersecting);
중괄호 린트룰 좋은 거 같아요
저도 if 한줄 방지 좋습니다

2022-01-04 15:04 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +                )}
아 좋네요 이 부분이야 말로 useMemo로 최적화할 수 있는 부분이 맞는 거 같아요

2022-01-04 15:05 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +                userId={userId || 1}
아 맞아요 이제는 빠져도 될 코드죠~

2022-01-04 15:05 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +                userId={userId || 1}
뺄게요~!

2022-01-04 15:09 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +  const sensorRef = useRef<HTMLDivElement>(null);
ref의 앞에 붙어야 할 단어라고 한다면 ref와 target은 의미적으로 같다고 생각해요 그래서 target이라는 이름이 살짝 포괄적이지 않나 싶어요

sensor처럼 target보다 구체적인 것이 와주면 좋을 거같아요
ex) sensorRef, modalRef 등

2022-01-04 15:12 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +              <Link href={`/user/menu`} passHref>
저도 그런 고민이 들긴하는데요

상수화한다면 전역을 바꾸는 게 한번에 되는 것이 의미라고 생각하는데
이런것을 상수화한다면 한번에 바꿀 수는 있겠지만 변수명을 뭐라고 지어야할지 참막막하긴하네요

예를 들어
const MENU_URL = '/user/menu';
였다면 
/user/menu가 /user/setting로 이름이 바뀌었을때
MENU_URL을 결국 SETTING_URL로 바꿔야 하고 오히려 두번 일을 해야되지 않을까라는 걱정이 되요

한나는 어떻게 생각해요?

2022-01-04 15:12 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +  const sensorRef = useRef<HTMLDivElement>(null);
저는 sensor는 감지를 당하는 대상이 아니라 감지를 하는 물체에 보통 사용되는 것 같아요! 좀 더 감지 대상을 뜻하는 용어이면 좋겠는데 변수명 짓기가 어렵기는 하네용... 이 부분은 일단 넘어가도 될 듯 합니다🙂

2022-01-04 15:16 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +  const sensorRef = useRef<HTMLDivElement>(null);
옴 근데 이 ref는 sensor감지하는 element가 맞아요~
이 부분이 인터섹션되면서 sensor처럼 활용되는 부분이거든요
그치만 오해를 살 수 있다면 더 명확한걸로 고민해볼게요~

2022-01-04 15:19 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +  const sensorRef = useRef<HTMLDivElement>(null);
인터섹션 옵저버가 센서구 ref가 감지 대상인 거 아닐까용??

2022-01-04 15:22 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +              <Link href={`/user/menu`} passHref>
뭔가 한다면 url.MENU 요런 형태가 될 것 같두 url 변경이 일어나더라도 엄청 많은 양은 아닐 거라는 생각이 들어서, 찾아 바꾸기 하면 된다고 생각해요! 이 부분은 type도 딱히 없으니 human error가 나기 쉬운 부분이니 저는 전역 상수화 하는 방향으로 가고 싶어요~!

2022-01-04 15:23 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +  const sensorRef = useRef<HTMLDivElement>(null);
인터섹션 옵저버가 달린 탑네비게이션의 센서엘리먼트가 교차되는 것을 감지하고 있다고 생각했어요
모달의 ref가 modalRef라면
그렇다면 이 엘리먼트의 ref는 sesorRef가 아닐까 했어요

그나저나 정희님이랑 이런 대화 너무 즐겁네요...ㅠㅠ 그리웟어요 이런 여유

2022-01-04 15:26 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +              <Link href={`/user/menu`} passHref>
찾아바꾼다면 string으로 쓰는 것과 다름이 없다고 생각하는데 혹시 url.MENU 가 더 찾아내기가 쉬울까요?
ctrl + F에서 url.MENU가 더 찾기 쉬울 거 같기도 하구 흠 더 좋은 방법이 없을까 싶어요

우리 말고도 이런 걸 고민했을 거 같아서...

음 근데 확실한건

const url.MENU = '/user/menu' 에서 '/menu' 로 바뀐다면 유용하겠네요!! 씁시다이!

2022-01-05 00:10 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +  const sensorRef = useRef<HTMLDivElement>(null);
마누 말을 참고했을 때, 센서 엘리먼트가 감지 대상인 거 같아요~ sensor보다는 sensoredRef가 더 낫지 않나 싶어요!

2022-01-05 00:13 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +                  "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png"
저는... 아바타의 default 이미지는 한 군데에만 지역으로 있어도 되는 변수라고 생각해요!
profileImageUrl || Avatar.Link 와 같은 코드 중복이 불필요하다고 생각해서요

2022-01-05 00:17 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +              <Link href={`/user/menu`} passHref>
오 맞아요 후자의 경우!! 넘 좋은 것 같아요
마누 의견을 보고 생각해보니 url에 변수가 들어가는 경우도 있고, 종종 유틸 함수가 들어가는 경우도 있어서 이런 중복이 있을 경우 하나의 오류를 수정하면, 다른 곳의 오류도 수정해야 하는 불편함도 있더라구요!
일단 상수화, 함수화 진행해봐도 좋을 것 같습니다ㅎㅎ

2022-01-05 00:32 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +  const sensorRef = useRef<HTMLDivElement>(null);
홈... 감지되는 ref가 아니라 감지하는 ref이에요

한나말은 intersectionObserver가 element의 교차를 감지하고 있고 ref가 감지되니까라고 생각하는 것 같은데
sensorElement가 viewPort와 교차를 기다렸다가 상단바의 상태를 변경시키기 때문에 저는 TopNavigationSensor 자신이 sensor의 역할을 하고 있다고 생각해요

2022-01-05 00:32 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +                  "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png"
아 좀 더 명확히 말씀드려야 했는데

const CourtItem = {
  ShareButton,
  FavoritesToggle,
  ChatLink,
  KakaoMapLink,
  Header,
  Address,
  Datetime,
};
처럼

Avatar.Default
Avatar.Link
로 하면 props로 주는 거보다 좀 더 명확하지 않을까라는 거에요

2022-01-05 00:34 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +  const sensorRef = useRef<HTMLDivElement>(null);
넹 시각에 따라 다를 수 있을 것 같아서 이 부분은 고냥 넘어가도 될 것 같습니다!🙂

2022-01-05 00:40 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +    if (entry) setIsTopTransparent(entry.isIntersecting);
적합한 eslint룰 설정을 30분째 못찾고 있네요...

2022-01-05 00:43 UTC, limkhl commented on src/components/domain/TopNavigation/index.tsx
> +                  "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png"
아 이건 좀 다른 얘기긴 한데 현재 Avatar 컴포넌트에서 src에 들어가는 값이 null일 경우에 기본 이미지로 들어가게끔 되어 있어서 default parameter를 넣어주지 않아도 기본 이미지로 뜰 거예요!

2022-01-05 00:49 UTC, grighth12 commented on src/components/domain/TopNavigation/index.tsx
> +                  "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png"
음 저는 Avatar.~로 쓸 때는 어떤 차이로 나눈다기 보다 아예 다른 컴포넌트 일 때 쓰는 경우가 많아서, 요 경우에도 적합할 지는 고민이 되는 것 같아요. 저는 LinkAvatar + href props required로 충분히 명확하다고 생각합니다. namespace로 관련된 걸 묶어주려는 의도라고 받아들였는데, 저는 지금도 괜찮은 것 같습니다

어렵네요😅

2022-01-05 01:00 UTC, manudeli commented on src/components/domain/TopNavigation/index.tsx
> +    if (entry) setIsTopTransparent(entry.isIntersecting);
"curly": ["error", "all"] 아 찾아버렸습니다

2022-01-05 01:05 UTC, limkhl commented on src/components/domain/TopNavigation/index.tsx
> +                  "https://upload.wikimedia.org/wikipedia/commons/8/89/Portrait_Placeholder.png"
Avatar.~ 이런 컴포넌트명은 Menu.Group, Menu.Item처럼 조합할 때 쓰는 것 같아서 Avatar.Link는 약간 의미상으로 어색한 느낌이 드는 것 같기도요. 저도 지금도 괜찮은 것 같고요!

2022-01-05 01:08 UTC, limkhl reviewed
저는 한나가 얘기한 부분 반영되면 머지되어도 좋은 것 같습니다! 👍 intersection observer 부분은 사실 아직 이해를 못했는데 좀 더 공부하고 useIntersectionObserver hook 코드도 훑어보고 그래도 이해 안 되는 부분은 여쭤보도록 할게요!

2022-01-05 01:39 UTC, manudeli commented
한나가 이야기한 부분 반영되어서 머지하겠습니다

2022-01-05 01:39 UTC, merged