예약 시스템 절대 시간으로 설계하기
prgrms-web-devcourse/slam-client pull request #231
Opened 2022-01-14 08:51 UTC by grighth12

## 💁 설명 

## 🔗 연결된 이슈 

closes

## 🚨 PR 포인트 

- 사항1

## 📸 스크린 샷

2022-01-16 00:00 UTC, manudeli requested changes
클라이언트의 위치가 서울과 시간차이가 날 수 있는 지역라고 가정하고 테스트를 해보시면 좋을 거 같아요
timezone에 대한 대응이 필요해보여요
이번 Review는 다른 국가로 가정하고 직접 테스트해보면서 좀 신경을 써봤어요 열심히 작업해주셨는데 엄청 request changes 리뷰를 많이 달어서 조금 미안한 마음이 있어요ㅠㅠ

시간이 좀 더 걸리더라도 더 깊이해서 이번 version1에서 명확히 끝내버립시다 파이팅!
혹시나 제가 잘못되었다고 생각하시는 부분 같이 공유해주시면 좋겠어요

2022-01-17 03:15 UTC, grighth12 commented on src/utils/date.ts
> +// TODO 추후 API 변경 시 dayjs utc 로 변경 예정
앞에 TODO 만 달아줘도 돼요!

2022-01-17 07:32 UTC, grighth12 commented on src/utils/date.ts
> +export const getIsOneHourLeft = (datetime: string) => {
date: dayjs 오브젝트
dateString: 년월일만 있는 문자열
datetime: 년월일시간을 포함한 문자열

요렇게 사용하고 있었는데요 마누 말씀대로 date : string으로 ts로 표현해줄 수 있으니 무의미한 것 같아요!! 

datetime -> iso: string으로 해도 괜찮을 것 같고... 저도 참 모호하다고 생각해서 한번 고쳐서 PR 올려보도록 할게요

혹시 마누도 의견이 있으시다면 나눠주신다면 감사하겠습니다🥲

2022-01-17 09:05 UTC, grighth12 commented on src/utils/date.ts
> +  dayjs().hour(0).minute(0).second(0).millisecond(0);
timezone 함수를 확인해보니, 지정해주지 않은 인자가 들어올 경우 런타임 에러가 발생하는 것으로 확인하였습니다
일단 타입지정해서 해당 타입만 들어가도록 해놓았어요!

2022-01-19 07:05 UTC, grighth12 commented on src/utils/date.ts
>  };
일단 서버에서 오는 데이터가 iso string이라는건 신뢰할 수 있다고 생각해서, 클라이언트 단에서 생각해보니 클라이언트 단에서는 iso string을 쓰지 않고 시간을 생성하는 경우가 있어서 요 부분은 적용하기 어려울 것 같습니다!

2022-01-19 07:09 UTC, grighth12 commented
리뷰 반영하여 머지합니다~

2022-01-19 07:09 UTC, merged